import 'package:videocalling_medical/common/utils/app_imports.dart';

class Words extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'ok_btn': 'Ok',
          'error': 'Error!',
          'error_s': 'Server Error!',
          'error_f': 'Firebase Error!',
          'error_c': 'ConnectyCube Error!',
          'firebase_not_add': 'Data not add in firebase try again',
          "PermissionsRequired" : "Permissions Required",
          "videocalldetail" : "Camera and microphone permissions are required to make a video call.",
          "audiocalldetail" : "Microphone permissions are required to make a audio call.",
          'error2': 'Please try again',
          'error3': 'Something Wrong',
          'unable_to_save_token': 'Unable to save token to server',
          'turn_on_location_and_retry': 'Turn on location and retry',
          'creating_account': 'Creating Account',
          'creating_account1': 'Please wait while creating account...',
          'creating_account_f': 'Add Account Detail In Firebase',
          'creating_account1_f': 'Please wait while adding account detail in firebase...',
          'creating_account_c': 'Add Account Detail In ConnectyCube',
          'creating_account1_c': 'Please wait while adding detail in ConnectyCube...',
          'yes_btn': 'Yes',
          'no_btn': 'No',
          'cancel': 'Cancel',
          'btn_submit': 'Submit',
          'logout_title': 'Logout',
          'logout_description': 'Are you sure to logout',
          'logout_loading_title': 'Log out',
          'logout_loading_description': 'Please wait while log out...',
          'success': 'Successful',
          'success_str': 'Success',
          'success_prescription': 'Prescription Order Successfully',
          'add_address1': 'Add a new address',
          'payment_success': 'Your payment success',
          'not_logged_in': 'You are not logged in',
          'reporting_dialog1': 'Processing',
          'reporting_dialog2': 'Please wait while reporting issue...',
          'reporting_dialog3': 'No issue selected',
          'edit_dialog1': 'Updating details',
          'edit_dialog2': 'Please wait while updating details',
          'login_dialog_title': 'Logging In',
          'login_dialog_description': 'Please wait while logging in...',
          'fail': 'Fail',
          'fail_description': 'Your payment fail try again',
          'appointment_made_success': 'Appointment made successfully',
          'appoint_make_dialog': 'Please wait while making appointment',
          'while_saving_changes': 'Please wait while saving changes',
          'receipt_uploading': 'Receipt Uploading...',
          'upload_receipt_des1': 'Upload Recipe Description and dummy text',
          'upload_receip': 'Upload Recipe',
          'remove_prescription': 'Remove Prescription',
          'upload_prescription': 'Upload Prescription',
          'prescription': 'Prescription',
          'continue_purchase': 'Continue To Purchase',
          'hello': 'Hello ',
          'choose_your_plan': 'CHOOSE YOUR PLAN',
          'choose_plan_t1': 'Monthly',
          'choose_plan_t2': 'Quarterly',
          'choose_plan_t3': 'HalfYear',
          'choose_plan_t4': 'Yearly',
          'd_subscription_plan_status1': 'Not Active',
          'd_subscription_plan_status2': 'Active',
          'd_subscription_plan_status3': 'Expire',
          'd_subscription_plan_status4': 'Reject',
          'month_str': 'Month',
          'save_str': 'Save 50%',
          'access_text': 'Access video calling',
          'available_text': '24/7 available',
          'choose_plan_des':
              'Doctor can purchase subscription and start using our app, after subscribe you can start dealing with your appointment, complete your profiles, set time slots, you can also check your reviews by users, and many more features',
          'call_dialog_title': 'Choose call type',
          'image_save_success': 'Image Save Successfully',
          'confirmation': 'Confirmation',
          'price_confirmation': 'Are you sure to send medicine price?',
          'delete': 'Delete',
          'delete_report': 'Are you want to sure delete this report?',
          'permission_not_granter': 'Permission not granted',
          'file_type_not_supported': 'File type not supported',
          'update_bank_details_dialog': 'Please wait while updating bank details',
          'update_bank_details_success': 'Bank detail update successful',
          'send_price': 'Send Price',
          'btn_complete': 'Complete',
          'btn_accept': 'Accept',
          'btn_cancel': 'Cancel',
          'btn_absent': 'Absent',
          'btn_upload': 'Upload',
          'profile_update_successfully': 'Profile updated successfully',

          /// tabs screen
          'home': 'Home',
          'appointment': 'Appointment',
          'doctor_login': 'Doctor login',
          'recent_chats': 'Recent chats',
          'app_medicine': 'App medicine',
          'more': 'More',
          'edit_profile': 'Edit profile',

          /// patient more screen
          'title1': 'Specialist',
          'title2': 'About',
          'title3': 'Term & Conditions',
          'title4': 'Report Issues',
          'title5': 'Logout',
          'sign_in_title': 'Sign In',
          'sign_in_title_1': 'Sign in to continue',
          'terms_and_conditions': 'Term & Conditions',
          'about': 'About us',
          'clear': 'Clear',
          'no_city': 'No cities available to sort',
          'unable_to_load_data': 'Something went wrong, Unable to load data',
          'report_issue1': 'Doctor not taking appointments on time',
          'report_issue2': 'Doctor is spam and details are incorrect',
          'report_issue3': 'Address details are incorrect',
          'report_issue4': 'Doctors not treating well',
          'report_issue5':
              'Doctor accepted appointment but when i visit assistant diagnosing patients',
          'report': 'Report',
          'description_hint': 'Describe your issue',
          'description_error': 'Description is necessary',
          'enter_name': 'Enter Name',
          'enter_number': 'Enter mobile number',
          'enter_email_hint': 'Enter your email',
          'enter_email_error': 'Enter valid email address',
          'password_not_match': 'Password doesn\'t match',
          'confirm_password': 'Confirm Password',
          'password': 'Password',
          'update': 'Update',
          'dont_upload': 'Don\'t Upload Photo? ',
          'skip': 'Skip',
          'upload_image': 'Upload Profile Image',
          'next': 'Next',
          'speciality': 'Speciality',
          'doctor_not_found': 'Doctors Not Found',
          'appointment_fee': 'Appointment Fee',
          'appointment_fee_small': 'appointment fee',
          'not_specified': 'Not specified',
          'book_now': 'Book Now',
          'phone_number': 'Phone number',
          'doctor_detail': 'Doctor detail',
          'see_all_review': 'See all reviews',
          'review_str': 'reviews',
          'review': 'Review',
          'login_to_review': 'Login to add review',
          'no_review': 'No reviews',
          'add_a_review': 'Add a review',
          'your_rating': 'Your rating',
          'enter_message': 'Enter your message',
          'wait_for_while': 'Wait for a while...',
          'uploading_review': 'Uploading review',
          'login_to_book_appointment': 'Login to book appointment',
          'address': 'Address',
          'select_address_error': 'Select address from map',
          'select_city_error': 'City Not Selected',
          'working_time': 'Working time',
          'services': 'Services',
          'health_care_str': 'Heatlhcare',
          'health_care': 'Health care',
          'no_chats_title': 'No recent chats',
          'no_chats_description_user':
              '"To initiate chat with doctor you need to book appointment first”',
          'no_chats_description_doctor':
              '"You can initiate chat with user from appointment detail”',
          'all_appointment': 'All appointments',
          'all_orders': 'All orders',
          'all_appointment1': 'Appointments',
          'pharmacy_order': 'Medicine order',
          'not_appointment1': 'You don\'t have any appointment',
          'not_appointment2': 'Find best doctors near you by speciality,',
          'not_appointment3': 'click here',
          'either_mobile_number_is_incorrect':
              'Either mobile number or password is incorrect',

          /// textfield error
          'valid_mobile_number': 'Enter valid mobile number',
          'description': 'Description',
          'common_textfield_error': 'This field is required',
          'please_select_image': 'Please select image',
          'enter_report_hint': 'Enter report name',
          'enter_report_error': 'Please enter report name',
          'search_medicine_error': 'Please enter medicine name',
          'search_medicine_hint': 'Search medicine',
          'add_new_medicine': 'Add as new medicine',
          'add_medicine': 'Add medicine',
          'add_medicine_plus': 'Add medicine +',
          'name_label': 'Enter Medicine Name',
          'type_label': 'Enter Medicine Type',
          'type_error': 'Please Enter Medicine Type',
          'dosage_label': 'Enter Medicine Dosage',
          'dosage_error': 'Please Enter Medicine Dosage',
          'medicine_time_error': 'Please Enter medicine time',
          'about_us_error': 'Enter about us',
          'services_error': 'Enter services',
          'working_error': 'Enter working time',
          'select_department_hint': 'Select department',
          'select_login_type': 'Select login type',
          'name_hint': 'Name',
          'login_as_doctor': 'Login as Doctor',
          'login_as_pharmacy': 'Login as Pharmacy',

          /// register text
          'already_have_an_account': 'Already have an account?',
          'not_have_an_account': 'Don\'t have account?',
          'register': 'Register',
          'doctor_register': 'Register as doctor',
          'pharmacy_register': 'Register as pharmacy',
          'register_now': ' Register Now',
          'forget_password': 'Forget Password ?',
          'login_now': 'Login Now',
          'login': 'Login',
          'remove': 'Remove',
          'enter_6_characters': 'Please Enter atleast 6 characters',
          'either_email_password_incorrect': 'Either email or password is incorrect',
          'mobile_error_1': 'Please Enter mobile Number',
          'mobile_error_2': 'Please Enter atleast @length digits',
          'password_error': 'Password doesn\'t match',
          'password_error1': 'Please Enter Confirm Password',
          'password_error2': 'Please Enter atleast @length characters',
          'forget_password_enter_email':
              'Enter the email address associated with your account',
          'we_will_email_a_password_reset_link':
              'We will email you a link to reset you password',
          'please_wait_while_processing': 'Please wait while processing...',
          'loading': 'Loading...',
          'welcome_str': 'Welcome ',
          'user_str': 'User',
          'continue_with_google': 'Continue with google',
          'month1': 'Jan',
          'month2': 'Feb',
          'month3': 'March',
          'month4': 'April',
          'month5': 'May',
          'month6': 'June',
          'month7': 'July',
          'month8': 'Aug',
          'month9': 'Sep',
          'month10': 'Oct',
          'month11': 'Nov',
          'month12': 'Dec',
          'month_full_1': 'January',
          'month_full_2': 'February',
          'month_full_3': 'March',
          'month_full_4': 'April',
          'month_full_5': 'May',
          'month_full_6': 'June',
          'month_full_7': 'July',
          'month_full_8': 'August',
          'month_full_9': 'September',
          'month_full_10': 'October',
          'month_full_11': 'November',
          'month_full_12': 'December',
          'day1': 'Sun',
          'day2': 'Mon',
          'day3': 'Tue',
          'day4': 'Wed',
          'day5': 'Thu',
          'day6': 'Fri',
          'day7': 'Sat',
          'day_full_1': 'Monday',
          'day_full_2': 'Tuesday',
          'day_full_3': 'Wednesday',
          'day_full_4': 'Thursday',
          'day_full_5': 'Friday',
          'day_full_6': 'Saturday',
          'day_full_7': 'Sunday',
          'day_text_1': '1 Day',
          'day_text_2': '2 Days',
          'day_text_3': '3 Days',
          'day_text_4': '4 Days',
          'day_text_5': '5 Days',
          'day_text_6': '6 Days',
          'day_text_7': '7 Days',
          'day_text_8': '8 Days',
          'day_text_9': '9 Days',
          'day_text_10': '10 Days',
          'doc_on_leave_title': 'Doctor on leave',
          'doc_on_leave_description':
              'Not possible to book appointment on @date as doctor in on leave',
          'make_an_appointment': 'Make an appointment',
          'process_payment': 'Process Payment',
          'consultation_fee': 'Consultation fee',
          'consultation_fee_small': 'consultation fee',
          'select_a_payment_method': 'Select payment method',
          'method1_title': 'Cash On Board',
          'method1_description': 'Pay only on visiting doctor at your appointment time',
          'method2_title': 'Paystack',
          'method3_title': 'Rave',
          'method4_title': 'Paytm',
          'method5_title': 'Braintree',
          'method5_description':
              'use your credit/debit card or PayPal account to pay consultation fee',
          'method6_title': 'Stripe',
          'method6_description': 'use your credit/debit card to pay consultation fee',
          'method7_title': 'Razorpay',
          'common_description': 'use your credit/debit card to pay @type',
          'no_slot_available': 'No slot available',
          'past_time_slots': 'You can\'t select past time slots',
          'select_appointment_time': 'Please select appointment time',
          'upload_receipt': 'Upload Receipt',
          'upload_receipt_des': 'Upload Payment Receipt',
          'make_an_subscribe': 'Make an subscribe',

          /// appointment details
          'user_no_prescription_msg':
              'You do not have any prescription yet, Doctor will add after consultation.',
          'user_no_prescription_msg1': 'Here is your prescription.',
          'user_no_report_msg':
              'You do not have any Reports yet, Doctor will suggest if required after consultation.',
          'user_no_report_msg1': 'Here is your report.',
          'appointment_status_1': 'Absent',
          'appointment_status_2': 'Received',
          'appointment_status_3': 'Approved',
          'appointment_status_4': 'In Process',
          'appointment_status_5': 'Completed',
          'appointment_status_6': 'Rejected',

          'order_status_0': 'Received',
          'order_status_1': 'Accept',
          'order_status_2': 'Reject',
          'order_status_3': 'Completed',
          'order_status_4': 'In Process',
          'order_status_5': 'Waiting',
          'order_status_6': 'Cancel',
          'order_status_7': 'Prepared',
          'order_status_8': 'Out for Delivery',
          'order_status_9': 'Completed',
          'prepared': 'Prepared',
          'delivered': 'Delivered',

          'email_address': 'Email Address',
          'consume_it_days': 'Consume it for @days Days',
          'download_prescription': 'Download prescription',
          'medicine_param1': 'Type',
          'medicine_param2': 'Dosage',
          'medicine_param3': 'Time',
          'medicine_param4': 'Edit',
          'nearby_doctors': 'Nearby Doctors',
          'search_doctor_appbar1': 'search, ',
          'search_doctor_appbar2': 'Here',
          'search_doctor_name': 'Search doctor by name',
          'change_password_str': 'Change Password',
          'old_pwd': 'Old Password',
          'new_pwd': 'New Password',
          'old_pwd_error': 'Please Enter Old Password',
          'new_pwd_error': 'Please Enter New Password',
          'conf_pwd_error': 'Please Enter Confirm Password',
          'subscription_list': 'Subscription List',
          'subscription_str': 'Subscription',
          'income_report_tile_text1': 'Today\'s Earning Report',
          'income_report_tile_text2': 'Last 7 Days Earning Report',
          'income_report_tile_text3': 'Last 30 Days Earning Report',
          'income_report_tile_short_text1': 'Today\'s',
          'income_report_tile_short_text2': 'Last 7 day\'s',
          'income_report_tile_short_text3': 'Last 30 day\'s',
          'income_report_tile_text4': 'Select Date Range',
          'income_report_str': 'Income Report',
          'detailed_report': 'Detailed Reports',
          'total_income_str': '@option total income',
          'filter_report_by': 'Filter Reports by',
          'not_any_income_str': '@option you have not any income.',

          /// chat screen
          'media_upload_title': 'Choose type',
          'send_text_field_hint': 'Type a message here...',
          'first_conversation_title': 'You didn\'t made any conversation yet',
          'first_conversation_title1': 'Say Hi',
          'first_conversation_title2': 'No Conversations',
          'seen_str': 'seen ',
          'send_file': 'Sending File',
          'uploading_file': 'Uploading File',
          'uploading_file1': 'Uploading file...',
          'chat_title_today': 'Today',
          'chat_title_yesterday': 'Yesterday',
          'accept_chat_dialog_text1': 'Reject',
          'accept_chat_dialog_text2': 'Accept',
          'photo_str': 'Photo',
          'video_str': 'Video',
          'chat_time_yesterday': 'yesterday',
          'chat_time_day_ago': '@day days ago',
          'remove_msg_title': 'Remove Message',
          'remove_msg_subtitle': 'Are you sure to remove this message ?',

          'bank_details': 'Bank details',
          'update_bank_details': 'Update bank details',
          'account_name': 'Account holder name',
          'account_number': 'Account number',
          'conf_account_number': 'Confirm account number',
          'conf_account_number_error': 'Enter confirm account number',
          'conf_account_number_not_matched_error': 'Account number Not Matched!',
          'account_ifsc': 'IFSC code',
          'bank_name': 'Bank name',
          'account_name_error': 'Enter account holder name',
          'account_number_error': 'Enter account number',
          'account_ifsc_error': 'Enter IFSC code',
          'bank_name_error': 'Enter bank name',
          'more_info': 'More Info',
          'no_address': 'Address goes here...',
          'choose_gallery': 'Choose from gallery',
          'doctor_not_appointment_text': 'You don\'t have any appointment',
          'pharmacy_not_order_text': 'You don\'t have any order',
          'd_add_prescription_msg':
              'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
          'd_add_report_msg':
              'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
          'add_prescription': 'Add Prescription',
          'send_prescription': 'Send Prescription',
          'medicine_param_1': 'Type :',
          'medicine_param_2': 'Dosage :',
          'medicine_param_3': 'Consuming Time :',
          'medicine_param_4': 'Consuming is for :',
          'medicine_param_5': 'Consume it for :',
          'add_reports': 'Add Reports',
          'upload_report': 'Upload Report',
          'complete_appointment_subtitle':
              'Are you sure you want to complete this appointment?',
          'delete_medicine': 'Are you want to sure delete this medicine?',
          'medicine_str': 'Medicine',
          'add_medicine_str': 'Add medicine',
          'edit_medicine_str': 'Edit Medicine',
          'edit_data_btn': 'Edit Data',
          'add_to_prescription_btn': 'Add To Prescription',
          'call_accept_dialog_title': 'Call Accepting',
          'call_accept_dialog_subtitle': 'Please wait your call is accepting...',
          'doctor_dashboard': 'Doctor dashboard',
          'pharmacy_dashboard': 'Pharmacy dashboard',
          'appointments_str': 'Appointments',
          'order_str': 'Order',
          'see_all': 'see all',
          'pdf_downloading': 'Pdf Downloading...',
          'downloading_done': 'Downloading Done !',
          'pdf_downloader': 'Pdf Downloader',
          'upcoming_appointments': 'Upcoming Appointments',
          'min_str': 'Min',
          'profile_str': 'Profile',
          'start_time': 'Start time',
          'end_time': 'End time',
          'save': 'Save',
          'am_str': ' AM',
          'pm_str': ' PM',
          'empty_str': 'Empty',
          'no_changes_made': 'No changes have been made',
          'end_time_small_then_start_time':
              'Ending time can\'t be smaller than starting time',
          'timing_wrong': 'Timings entered incorrectly',
          'select_interval': 'Select interval',
          'start_end_time_wrong': 'Start/End time not entered correctly',
          'time_slot_added_successfully': 'Time Slot Added Successfully',
          'no_holiday_title': 'No holidays so far',
          'no_holiday_subtitle': 'Your holiday list will appear here',
          'add_holiday': 'Add Holiday',
          'update_holiday': 'Update Holiday',
          'select_date': 'Select Date',
          'select_time': 'Select Time',
          'select_date_desc':
              'Select a date or a number of dates for adding then to your holidays list',
          'add_date_error': 'Please select a date to add it in your holiday list',
          'days_holiday': ' Days Holiday',
          'data_not_found': 'Data Not found!',
          'specialist': ' specialist',
          'ringing': 'Ringing',
          'audio_call': 'Audio call',
          'members': 'Members:',
          'permission_not_granted': 'Permission not granted',
          'permission_not':
              'We required location permission to server you nearby doctors.',
          'call_accept_subtitle':
              'For accepting the calls in the background you should provide access to show System Alerts from the background. Would you like to do it now?',
          'call_accept_title': 'Permission required',
          'doctors': 'Doctors',
          'pharmacy': 'Pharmacy',
          'pharmacy_detail': 'Pharmacy detail',
          'view_medicine': 'View Medicines',
          'order_medicine1': 'Order Medicines',
          'address_not_found': 'Address not found',
          'order_detail_message':
              "You can send photos of your prescription to the pharmacy, and they will deliver the medications right to your doorstep.",
          'pharmacy_medicine': 'Pharmacy Medicines',
          'add_to_cart': 'Add to cart',
          'add_to_cart2': 'Add to Cart',
          'added': 'Added',
          'item': 'item',
          'checkout': 'Checkout',
          'view_cart': 'View cart',
          'view_cart1': 'View Cart',
          'cart': 'Cart',
          'cart_empty': 'Your cart is empty.',
          'medicine_price': 'Price :',
          'proceed_order': 'Proceed order',
          'total_price': 'Total price :',
          'total_price1': 'Total price',
          'total_mrp': 'Total MRP',
          'delivery_charges': 'Delivery charges',
          'tax': 'Tax',
          'order_medicine': 'Order Medicine',
          'total_medicine': 'Total medicine :',
          'proceed_payment': 'Proceed with Payment',
          'enter_name_error': 'Please enter name',
          'cart_exist_text': 'Medicines already in cart',
          'select_address_title': 'Select Address',
          'select_address': '+ Select Address',
          'add_address': '+ Add address',
          'add_address_title': 'Add Address',
          'update_address_title': 'Update Address',
          'your_location': 'Your location',
          'default_address': 'Default Address',
          'default': 'Default',
          'save_as': 'Save as',
          'save_as_error': 'Please enter text',
          'order_now': 'Order now',
          'delivery_address': 'Delivery address',
          'medicine_detail': 'Medicine Detail',
          'prescription_detail': 'Prescription Detail',
          'price_detail': 'Price Detail',
          'pharmacy_price_detail': 'Pharmacy send your prescription medicine price',
          'select_above_address': 'Select',
          'quantity_col': 'quantity: ',
          'price_col': 'Price: ',

          'please_select_address': 'Please select address',
          'enter_message_title': 'Enter message',
          'login_to_proceed_order': 'Login to proceed order',
          'order_medicine_dialog_title': 'Please wait while order medicine for you.',
          'cart_exist_text1':
              'Your cart contains medicines from other pharmacy. Would you like to reset your cart for adding medicines from this pharmacy?',
          'select_medicine_error': 'Please select atleast one medicine for add to cart',

          ///add new for pharmacy
          'all_order': 'Medicine Order',
          'already_added': 'Medicine already added in cart',
          "order_id": "Order ID : ",
          "medicine_hint": "Enter medicine price",
          "send_btn": "Send",
          "empty_price": "This field cannot be empty",
  'no_delivery_address':"No delivery address",

        },
        'ar_AR': {
          'ok_btn': 'حسنًا',
          'error': 'خطأ!',
          "PermissionsRequired" : "الأذونات المطلوبة",
          "videocalldetail" : "مطلوب أذونات الكاميرا والميكروفون لإجراء مكالمة فيديو.",
          "audiocalldetail" : "يجب الحصول على أذونات الميكروفون لإجراء مكالمة صوتية.",
          'error2': 'يرجى المحاولة مرة أخرى',
          'error3': 'حدث خطأ ما',
          'unable_to_save_token': 'تعذر حفظ الرمز على الخادم',
          'turn_on_location_and_retry': 'قم بتشغيل الموقع وأعد المحاولة',
          'creating_account': 'إنشاء حساب',
          'creating_account1': 'يرجى الانتظار أثناء إنشاء الحساب...',
          'yes_btn': 'نعم',
          'no_btn': 'لا',
          'cancel': 'إلغاء',
          'btn_submit': 'إرسال',
          'logout_title': 'تسجيل الخروج',
          'logout_description': 'هل أنت متأكد أنك تريد تسجيل الخروج؟',
          'logout_loading_title': 'تسجيل الخروج',
          'logout_loading_description': 'يرجى الانتظار أثناء تسجيل الخروج...',
          'success': 'نجاح',
          'success_str': 'ناجح',
          'success_prescription': 'تم الطلب بنجاح',
          'add_address1': 'أضف عنوانًا جديدًا',
          'payment_success': 'تم الدفع بنجاح',
          'not_logged_in': 'أنت غير مسجل الدخول',
          'reporting_dialog1': 'جارٍ المعالجة',
          'reporting_dialog2': 'يرجى الانتظار أثناء الإبلاغ عن المشكلة...',
          'reporting_dialog3': 'لم يتم تحديد مشكلة',
          'edit_dialog1': 'جارٍ تحديث التفاصيل',
          'edit_dialog2': 'يرجى الانتظار أثناء تحديث التفاصيل...',
          'login_dialog_title': 'تسجيل الدخول',
          'login_dialog_description': 'يرجى الانتظار أثناء تسجيل الدخول...',
          'fail': 'فشل',
          'fail_description': 'فشل الدفع الخاص بك، حاول مرة أخرى',
          'appointment_made_success': 'تم تحديد الموعد بنجاح',
          'appoint_make_dialog': 'يرجى الانتظار أثناء تحديد الموعد...',
          'while_saving_changes': 'يرجى الانتظار أثناء حفظ التغييرات...',
          'receipt_uploading': 'جارٍ تحميل الإيصال...',
          'upload_receipt_des1': 'تحميل وصفة الطبخ والوصف النصي التجريبي',
          'upload_receip': 'تحميل الوصفة',
          'remove_prescription': 'إزالة الوصفة',
          'upload_prescription': 'تحميل الوصفة',
          'prescription': 'الوصفة',
          'continue_purchase': 'متابعة الشراء',
          'hello': 'مرحبًا ',
          'choose_your_plan': 'اختر خطتك',
          'choose_plan_t1': 'شهري',
          'choose_plan_t2': 'ربع سنوي',
          'choose_plan_t3': 'نصف سنوي',
          'choose_plan_t4': 'سنوي',
          'd_subscription_plan_status1': 'غير نشط',
          'd_subscription_plan_status2': 'نشط',
          'd_subscription_plan_status3': 'منتهي',
          'd_subscription_plan_status4': 'مرفوض',
          'month_str': 'شهر',
          'save_str': 'وفر 50%',
          'access_text': 'الوصول إلى المكالمات بالفيديو',
          'available_text': 'متاح 24/7',
          'choose_plan_des':
              'يمكن للطبيب شراء الاشتراك وبدء استخدام تطبيقنا، بعد الاشتراك يمكنك البدء في إدارة مواعيدك، إكمال ملفك الشخصي، تحديد أوقات العمل، كما يمكنك مراجعة تقييمات المستخدمين والعديد من الميزات الأخرى',
          'call_dialog_title': 'اختر نوع المكالمة',
          'image_save_success': 'تم حفظ الصورة بنجاح',
          'confirmation': 'تأكيد',
          'price_confirmation': 'هل أنت متأكد من إرسال سعر الدواء؟',
          'delete': 'حذف',
          'delete_report': 'هل تريد بالتأكيد حذف هذا التقرير؟',
          'permission_not_granter': 'لم يتم منح الإذن',
          'file_type_not_supported': 'نوع الملف غير مدعوم',
          'update_bank_details_dialog': 'يرجى الانتظار أثناء تحديث تفاصيل البنك...',
          'update_bank_details_success': 'تم تحديث تفاصيل البنك بنجاح',
          'send_price': 'إرسال السعر',
          'btn_complete': 'اكتمال',
          'btn_accept': 'قبول',
          'btn_cancel': 'إلغاء',
          'btn_absent': 'غائب',
          'btn_upload': 'تحميل',
          'profile_update_successfully': 'تم تحديث الملف الشخصي بنجاح',

          ///
          'home': 'الرئيسية',
          'appointment': 'المواعيد',
          'doctor_login': 'تسجيل دخول الطبيب',
          'recent_chats': 'الدردشات الأخيرة',
          'app_medicine': 'تطبيق الدواء',
          'more': 'المزيد',
          'edit_profile': 'تعديل الملف الشخصي',

          ///

          'title1': 'أخصائي',
          'title2': 'حول',
          'title3': 'الشروط والأحكام',
          'title4': 'الإبلاغ عن مشكلات',
          'title5': 'تسجيل الخروج',
          'sign_in_title': 'تسجيل الدخول',
          'sign_in_title_1': 'قم بتسجيل الدخول للمتابعة',
          'terms_and_conditions': 'الشروط والأحكام',
          'about': 'معلومات عنا',
          'unable_to_load_data': 'حدث خطأ ما، غير قادر على تحميل البيانات',
          'report_issue1': 'الطبيب لا يأخذ المواعيد في الوقت المحدد',
          'report_issue2': 'الطبيب غير موثوق والمعلومات غير صحيحة',
          'report_issue3': 'تفاصيل العنوان غير صحيحة',
          'report_issue4': 'الأطباء لا يعالجون المرضى بشكل جيد',
          'report_issue5': 'الطبيب قبل الموعد ولكن عند زيارتي كان المساعد يعالج المرضى',
          'report': 'الإبلاغ',
          'description_hint': 'وصف مشكلتك',
          'description_error': 'الوصف مطلوب',
          'enter_name': 'أدخل الاسم',
          'enter_number': 'أدخل رقم الجوال',
          'enter_email_hint': 'أدخل بريدك الإلكتروني',
          'enter_email_error': 'أدخل عنوان بريد إلكتروني صالح',
          'password_not_match': 'كلمة المرور غير مطابقة',
          'confirm_password': 'تأكيد كلمة المرور',
          'password': 'كلمة المرور',
          'update': 'تحديث',
          'dont_upload': 'لا تريد تحميل الصورة؟',
          'skip': 'تخطي',
          'upload_image': 'تحميل صورة الملف الشخصي',
          'next': 'التالي',
          'speciality': 'التخصص',
          'doctor_not_found': 'لم يتم العثور على أطباء',
          'appointment_fee': 'رسوم الموعد',
          'appointment_fee_small': 'رسوم الموعد',
          'not_specified': 'غير محدد',
          'book_now': 'احجز الآن',
          'phone_number': 'رقم الهاتف',
          'doctor_detail': 'تفاصيل الطبيب',
          'see_all_review': 'عرض جميع التقييمات',
          'review_str': 'التقييمات',
          'review': 'تقييم',
          'login_to_review': 'سجل الدخول لإضافة تقييم',
          'no_review': 'لا توجد تقييمات',
          'add_a_review': 'إضافة تقييم',
          'your_rating': 'تقييمك',
          'enter_message': 'أدخل رسالتك',
          'wait_for_while': 'يرجى الانتظار...',
          'uploading_review': 'جاري تحميل التقييم',
          'login_to_book_appointment': 'سجل الدخول لحجز موعد',
          'address': 'العنوان',
          'select_address_error': 'اختر العنوان من الخريطة',
          'working_time': 'أوقات العمل',
          'services': 'الخدمات',
          'health_care_str': 'الرعاية الصحية',
          'health_care': 'الرعاية الصحية',
          'no_chats_title': 'لا توجد دردشات حديثة',
          'no_chats_description_user':
              '"لبدء الدردشة مع الطبيب، يجب عليك أولاً حجز موعد"',
          'no_chats_description_doctor':
              '"يمكنك بدء الدردشة مع المستخدم من تفاصيل الموعد"',
          'all_appointment': 'جميع المواعيد',
          'all_orders': 'جميع الطلبات',
          'all_appointment1': 'المواعيد',
          'pharmacy_order': 'طلب الأدوية',
          'not_appointment1': 'ليس لديك أي مواعيد',
          'not_appointment2': 'اعثر على أفضل الأطباء بالقرب منك حسب التخصص،',
          'not_appointment3': 'انقر هنا',
          'either_mobile_number_is_incorrect':
              'إما أن رقم الجوال أو كلمة المرور غير صحيحة',

          ///
          'valid_mobile_number': 'أدخل رقم جوال صالح',
          'description': 'الوصف',
          'common_textfield_error': 'هذا الحقل مطلوب',
          'please_select_image': 'يرجى تحديد صورة',
          'enter_report_hint': 'أدخل اسم التقرير',
          'enter_report_error': 'يرجى إدخال اسم التقرير',
          'search_medicine_error': 'يرجى إدخال اسم الدواء',
          'search_medicine_hint': 'ابحث عن الدواء',
          'add_new_medicine': 'أضف كدواء جديد',
          'add_medicine': 'أضف دواء',
          'add_medicine_plus': 'أضف دواء +',
          'name_label': 'أدخل اسم الدواء',
          'type_label': 'أدخل نوع الدواء',
          'type_error': 'يرجى إدخال نوع الدواء',
          'dosage_label': 'أدخل جرعة الدواء',
          'dosage_error': 'يرجى إدخال جرعة الدواء',
          'medicine_time_error': 'يرجى إدخال وقت تناول الدواء',
          'about_us_error': 'أدخل "نبذة عنا"',
          'services_error': 'أدخل الخدمات',
          'working_error': 'أدخل أوقات العمل',
          'select_department_hint': 'اختر القسم',
          'select_login_type': 'اختر نوع تسجيل الدخول',
          'name_hint': 'الاسم',
          'login_as_doctor': 'تسجيل الدخول كطبيب',
          'login_as_pharmacy': 'تسجيل الدخول كصيدلية',

          ///

          'already_have_an_account': 'هل لديك حساب؟',
          'not_have_an_account': 'ليس لديك حساب؟',
          'register': 'تسجيل',
          'doctor_register': 'التسجيل كطبيب',
          'pharmacy_register': 'التسجيل كصيدلية',
          'register_now': 'سجل الآن',
          'forget_password': 'نسيت كلمة المرور؟',
          'login_now': 'تسجيل الدخول الآن',
          'login': 'تسجيل الدخول',
          'remove': 'إزالة',
          'enter_6_characters': 'يرجى إدخال 6 أحرف على الأقل',
          'either_email_password_incorrect': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
          'mobile_error_1': 'يرجى إدخال رقم الجوال',
          'mobile_error_2': 'يرجى إدخال @length أرقام على الأقل',
          'password_error': 'كلمة المرور غير متطابقة',
          'password_error1': 'يرجى إدخال تأكيد كلمة المرور',
          'password_error2': 'يرجى إدخال @length أحرف على الأقل',
          'forget_password_enter_email': 'أدخل عنوان البريد الإلكتروني المرتبط بحسابك',
          'we_will_email_a_password_reset_link':
              'سوف نرسل لك رابطًا لإعادة تعيين كلمة المرور عبر البريد الإلكتروني',
          'please_wait_while_processing': 'يرجى الانتظار أثناء المعالجة...',
          'loading': 'جارٍ التحميل...',
          'welcome_str': 'مرحبًا ',
          'user_str': 'المستخدم',
          'continue_with_google': 'تابع مع جوجل',
          'month1': 'يناير',
          'month2': 'فبراير',
          'month3': 'مارس',
          'month4': 'أبريل',
          'month5': 'مايو',
          'month6': 'يونيو',
          'month7': 'يوليو',
          'month8': 'أغسطس',
          'month9': 'سبتمبر',
          'month10': 'أكتوبر',
          'month11': 'نوفمبر',
          'month12': 'ديسمبر',
          'month_full_1': 'يناير',
          'month_full_2': 'فبراير',
          'month_full_3': 'مارس',
          'month_full_4': 'أبريل',
          'month_full_5': 'مايو',
          'month_full_6': 'يونيو',
          'month_full_7': 'يوليو',
          'month_full_8': 'أغسطس',
          'month_full_9': 'سبتمبر',
          'month_full_10': 'أكتوبر',
          'month_full_11': 'نوفمبر',
          'month_full_12': 'ديسمبر',
          'day1': 'أحد',
          'day2': 'إثنين',
          'day3': 'ثلاثاء',
          'day4': 'أربعاء',
          'day5': 'خميس',
          'day6': 'جمعة',
          'day7': 'سبت',
          'day_full_1': 'الإثنين',
          'day_full_2': 'الثلاثاء',
          'day_full_3': 'الأربعاء',
          'day_full_4': 'الخميس',
          'day_full_5': 'الجمعة',
          'day_full_6': 'السبت',
          'day_full_7': 'الأحد',
          'day_text_1': '1 يوم',
          'day_text_2': '2 يومين',
          'day_text_3': '3 أيام',
          'day_text_4': '4 أيام',
          'day_text_5': '5 أيام',
          'day_text_6': '6 أيام',
          'day_text_7': '7 أيام',
          'day_text_8': '8 أيام',
          'day_text_9': '9 أيام',
          'day_text_10': '10 أيام',
          'doc_on_leave_title': 'الطبيب في إجازة',
          'doc_on_leave_description': 'لا يمكن حجز موعد في @date لأن الطبيب في إجازة',
          'make_an_appointment': 'حجز موعد',
          'process_payment': 'إتمام الدفع',
          'consultation_fee': 'رسوم الاستشارة',
          'consultation_fee_small': 'رسوم الاستشارة',
          'select_a_payment_method': 'اختر طريقة الدفع',
          'method1_title': 'الدفع عند الحضور',
          'method1_description': 'ادفع عند زيارة الطبيب في موعدك',
          'method2_title': 'باي ستاك',
          'method3_title': 'ريف',
          'method4_title': 'باي تي إم',
          'method5_title': 'براين تري',
          'method5_description':
              'استخدم بطاقة الائتمان/الخصم أو حساب PayPal لدفع رسوم الاستشارة',
          'method6_title': 'سترايب',
          'method6_description': 'استخدم بطاقة الائتمان/الخصم لدفع رسوم الاستشارة',
          'method7_title': 'رازورباي',
          'common_description': 'استخدم بطاقة الائتمان/الخصم لدفع @type',
          'no_slot_available': 'لا يوجد موعد متاح',
          'past_time_slots': 'لا يمكنك اختيار مواعيد سابقة',
          'select_appointment_time': 'يرجى اختيار وقت الموعد',
          'upload_receipt': 'تحميل الإيصال',
          'upload_receipt_des': 'تحميل إيصال الدفع',
          'make_an_subscribe': 'الاشتراك',

          ///

          "user_no_prescription_msg":
              "ليس لديك أي وصفة طبية حتى الآن، سيقوم الطبيب بإضافتها بعد الاستشارة.",
          "user_no_prescription_msg1": "ها هي وصفتك.",
          "user_no_report_msg":
              "ليس لديك أي تقارير حتى الآن، سيقترح الطبيب إذا لزم الأمر بعد الاستشارة.",
          "user_no_report_msg1": "ها هو تقريرك.",
          "appointment_status_1": "غائب",
          "appointment_status_2": "مستلم",
          "appointment_status_3": "معتمد",
          "appointment_status_4": "قيد المعالجة",
          "appointment_status_5": "مكتمل",
          "appointment_status_6": "مرفوض",
          "order_status_0": "مستلم",
          "order_status_1": "قبول",
          "order_status_2": "رفض",
          "order_status_3": "مكتمل",
          "order_status_4": "قيد المعالجة",
          "order_status_5": "في الانتظار",
          "order_status_6": "إلغاء",
          "order_status_7": "مجهز",
          "order_status_8": "في طريق التسليم",
          "order_status_9": "مكتمل",
          "prepared": "مجهز",
          "delivered": "تم التوصيل",
          "email_address": "عنوان البريد الإلكتروني",
          "consume_it_days": "تناوله لمدة @days يومًا",
          "download_prescription": "تحميل الوصفة",
          "medicine_param1": "النوع",
          "medicine_param2": "الجرعة",
          "medicine_param3": "الوقت",
          "medicine_param4": "تعديل",
          "nearby_doctors": "الأطباء القريبون",
          "search_doctor_appbar1": "بحث، ",
          "search_doctor_appbar2": "هنا",
          "search_doctor_name": "ابحث عن طبيب بالاسم",
          "change_password_str": "تغيير كلمة المرور",
          "old_pwd": "كلمة المرور القديمة",
          "new_pwd": "كلمة المرور الجديدة",
          "old_pwd_error": "يرجى إدخال كلمة المرور القديمة",
          "new_pwd_error": "يرجى إدخال كلمة المرور الجديدة",
          "conf_pwd_error": "يرجى إدخال كلمة المرور المؤكدة",
          "subscription_list": "قائمة الاشتراك",
          "subscription_str": "الاشتراك",
          "income_report_tile_text1": "تقرير الأرباح اليومي",
          "income_report_tile_text2": "تقرير الأرباح لآخر 7 أيام",
          "income_report_tile_text3": "تقرير الأرباح لآخر 30 يومًا",
          "income_report_tile_short_text1": "اليوم",
          "income_report_tile_short_text2": "آخر 7 أيام",
          "income_report_tile_short_text3": "آخر 30 يومًا",
          "income_report_tile_text4": "حدد نطاق التاريخ",
          "income_report_str": "تقرير الدخل",
          "detailed_report": "تقارير مفصلة",
          "total_income_str": "@option إجمالي الدخل",
          "filter_report_by": "تصفية التقارير حسب",
          "not_any_income_str": "@option ليس لديك أي دخل.",

          ///

          "media_upload_title": "اختر النوع",
          "send_text_field_hint": "اكتب رسالة هنا...",
          "first_conversation_title": "لم تقم بإجراء أي محادثة حتى الآن",
          "first_conversation_title1": "قل مرحبًا",
          "first_conversation_title2": "لا محادثات",
          "seen_str": "شاهد",
          "send_file": "جارٍ إرسال الملف",
          "uploading_file": "جارٍ رفع الملف",
          "uploading_file1": "جارٍ رفع الملف...",
          "chat_title_today": "اليوم",
          "chat_title_yesterday": "أمس",
          "accept_chat_dialog_text1": "رفض",
          "accept_chat_dialog_text2": "قبول",
          "photo_str": "صورة",
          "video_str": "فيديو",
          "chat_time_yesterday": "أمس",
          "chat_time_day_ago": "منذ @day يومًا",
          "remove_msg_title": "إزالة الرسالة",
          "remove_msg_subtitle": "هل أنت متأكد من إزالة هذه الرسالة؟",
          "bank_details": "تفاصيل البنك",
          "update_bank_details": "تحديث تفاصيل البنك",
          "account_name": "اسم صاحب الحساب",
          "account_number": "رقم الحساب",
          "conf_account_number": "تأكيد رقم الحساب",
          "conf_account_number_error": "أدخل رقم الحساب المؤكد",
          "conf_account_number_not_matched_error": "رقم الحساب غير متطابق!",
          "account_ifsc": "رمز IFSC",
          "bank_name": "اسم البنك",
          "account_name_error": "أدخل اسم صاحب الحساب",
          "account_number_error": "أدخل رقم الحساب",
          "account_ifsc_error": "أدخل رمز IFSC",
          "bank_name_error": "أدخل اسم البنك",
          "more_info": "معلومات إضافية",
          "no_address": "العنوان هنا...",
          "choose_gallery": "اختر من المعرض",
          "doctor_not_appointment_text": "ليس لديك أي موعد",
          "pharmacy_not_order_text": "ليس لديك أي طلب",
          "d_add_prescription_msg":
              "Lorem Ipsum هو نص وهمي من صناعة الطباعة وتنسيق النصوص",
          "d_add_report_msg": "Lorem Ipsum هو نص وهمي من صناعة الطباعة وتنسيق النصوص",
          "add_prescription": "إضافة وصفة",
          "send_prescription": "إرسال وصفة",
          "medicine_param_1": "النوع:",
          "medicine_param_2": "الجرعة:",
          "medicine_param_3": "وقت الاستهلاك:",
          "medicine_param_4": "الاستهلاك لمدة:",
          "medicine_param_5": "تناوله لمدة:",
          "add_reports": "إضافة تقارير",
          "upload_report": "رفع تقرير",
          "complete_appointment_subtitle": "هل أنت متأكد أنك تريد إكمال هذا الموعد؟",
          "delete_medicine": "هل أنت متأكد من حذف هذه الدواء؟",
          "medicine_str": "دواء",
          "add_medicine_str": "إضافة دواء",
          "edit_medicine_str": "تعديل الدواء",
          "edit_data_btn": "تعديل البيانات",
          "add_to_prescription_btn": "إضافة إلى الوصفة",
          "call_accept_dialog_title": "قبول المكالمة",
          "call_accept_dialog_subtitle": "يرجى الانتظار، يتم قبول مكالمتك...",
          "doctor_dashboard": "لوحة تحكم الطبيب",
          "pharmacy_dashboard": "لوحة تحكم الصيدلية",
          "appointments_str": "المواعيد",
          "order_str": "طلب",
          "see_all": "عرض الكل",
          "pdf_downloading": "جارٍ تنزيل PDF...",
          "downloading_done": "اكتمل التنزيل!",
          "pdf_downloader": "تحميل PDF",
          "upcoming_appointments": "المواعيد القادمة",
          "min_str": "دقائق",
          "profile_str": "الملف الشخصي",
          "start_time": "وقت البدء",
          "end_time": "وقت الانتهاء",
          "save": "حفظ",
          "am_str": "صباحًا",
          "pm_str": "مساءً",
          "empty_str": "فارغ",
          "no_changes_made": "لم يتم إجراء أي تغييرات",
          "end_time_small_then_start_time":
              "لا يمكن أن يكون وقت الانتهاء أصغر من وقت البدء",
          "timing_wrong": "تم إدخال التوقيت بشكل غير صحيح",
          "select_interval": "اختر الفاصل الزمني",
          "start_end_time_wrong": "لم يتم إدخال وقت البدء/الانتهاء بشكل صحيح",
          "time_slot_added_successfully": "تم إضافة فترة الوقت بنجاح",
          "no_holiday_title": "لا عطلات حتى الآن",
          "no_holiday_subtitle": "ستظهر قائمة عطلاتك هنا",
          "add_holiday": "إضافة عطلة",
          "update_holiday": "تحديث العطلة",
          "select_date": "اختر تاريخًا",
          "select_time": "اختر وقتًا",
          "select_date_desc":
              "اختر تاريخًا أو عددًا من التواريخ لإضافتها إلى قائمة عطلاتك",
          "add_date_error": "يرجى اختيار تاريخ لإضافته إلى قائمة عطلاتك",
          "days_holiday": " أيام عطلة",
          "data_not_found": "البيانات غير موجودة!",
          "specialist": " متخصص",
          "ringing": "رنين",
          "audio_call": "مكالمة صوتية",
          "members": "الأعضاء:",
          "permission_not_granted": "لم يتم منح الإذن",
          "permission_not": "نحتاج إلى إذن الموقع لخدمتك بالأطباء القريبين.",
          "call_accept_subtitle":
              "للقبول في المكالمات في الخلفية، يجب عليك توفير الوصول لعرض تنبيهات النظام من الخلفية. هل ترغب في القيام بذلك الآن؟",
          "call_accept_title": "الإذن مطلوب",
          "doctors": "الأطباء",
          "pharmacy": "صيدلية",
          "pharmacy_detail": "تفاصيل الصيدلية",
          "view_medicine": "عرض الأدوية",
          "order_medicine1": "طلب أدوية",
          "address_not_found": "العنوان غير موجود",
          "order_detail_message":
              "يمكنك إرسال صور لوصفتك إلى الصيدلية، وسيقومون بتوصيل الأدوية إلى باب منزلك.",
          "pharmacy_medicine": "أدوية الصيدلية",
          "add_to_cart": "إضافة إلى السلة",
          "add_to_cart2": "أضف إلى السلة",
          "added": "يضيف",
          "checkout": "الدفع",
          "view_cart": "عرض السلة",
          "view_cart1": "عرض السلة",
          "cart": "السلة",
          "cart_empty": "سلتك فارغة.",
          "medicine_price": "السعر:",
          "proceed_order": "متابعة الطلب",
          "total_price": "إجمالي السعر:",
          "total_price1": "إجمالي السعر",
          "total_mrp": "إجمالي السعر المقترح",
          "delivery_charges": "رسوم التوصيل",
          "tax": "الضريبة",
          "order_medicine": "طلب دواء",
          "total_medicine": "إجمالي الدواء:",
          "proceed_payment": "متابعة الدفع",
          "enter_name_error": "يرجى إدخال الاسم",
          "cart_exist_text": "الأدوية موجودة بالفعل في السلة",
          "select_address_title": "اختر العنوان",
          "select_address": "+ اختر العنوان",
          "add_address": "+ أضف عنوانًا",
          "add_address_title": "إضافة عنوان",
          "update_address_title": "تحديث العنوان",
          "your_location": "موقعك",
          "default_address": "العنوان الافتراضي",
          "default": "افتراضي",
          "save_as": "احفظ كـ",
          "save_as_error": "يرجى إدخال نص",
          "order_now": "اطلب الآن",
          "delivery_address": "عنوان التوصيل",
          "medicine_detail": "تفاصيل الدواء",
          "prescription_detail": "تفاصيل الوصفة",
          "price_detail": "تفاصيل السعر",
          "pharmacy_price_detail": "ترسل الصيدلية لك سعر دوائك بوصفة",
          "select_above_address": "اختر",
          "quantity_col": "الكمية:",
          "price_col": "السعر:",
          "please_select_address": "يرجى اختيار عنوان",
          "enter_message_title": "أدخل الرسالة",
          "login_to_proceed_order": "تسجيل الدخول لمتابعة الطلب",
          "order_medicine_dialog_title": "يرجى الانتظار أثناء طلب الأدوية لك.",
          "cart_exist_text1":
              "تحتوي سلتك على أدوية من صيدلية أخرى. هل ترغب في إعادة تعيين سلتك لإضافة الأدوية من هذه الصيدلية؟",
          "select_medicine_error": "يرجى اختيار دواء واحد على الأقل لإضافته إلى السلة",

          ///
          "all_order": "طلب الأدوية",
          "already_added": "الدواء موجود بالفعل في السلة",
          "order_id": "معرف الطلب: ",
          'item': 'عنصر',
          'no_delivery_address':"لا يوجد عنوان للتوصيل",
          "medicine_hint": "أدخل سعر الدواء",
          "send_btn": "يرسل",
          "empty_price": "لا يمكن أن يكون هذا الحقل فارغا",





        },
    'de_DE': {
          'hello': 'Hallo Welt',
        }
      };
}
